//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NobleGasesMAUI.Elements.Helium {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Helium {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Helium() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NobleGasesMAUI.Elements.Helium.Helium", typeof(Helium).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Благородный газ нашел применение в разных областях. 
        ///
        ///Гелий, свойства которого позволяют получать сверхнизкие температуры, используется как охлаждающий агент в Большом адронном коллайдере, сверхпроводящих магнитах аппаратов МРТ и спектрометров ядерного магнитного резонанса, спутниковой аппаратуры, а также для сжижения кислорода и водорода в ракетах «Аполлон». 
        ///
        ///В качестве инертного газа для сварки алюминия и др. металлов, при производстве оптоволокна и полупроводников. 
        ///
        ///Для создания давления в топлив [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HeliumApplications {
            get {
                return ResourceManager.GetString("HeliumApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гелий был найден в газовой атмосфере, окружающей Солнце, французским астрономом Пьером Жансеном, который в 1868 году во время затмения обнаружил яркую желтую линию в спектре солнечной хромосферы. Первоначально предполагалось, что эта линия представляла элемент натрий. В том же году английский астроном Джозеф Норман Локьер наблюдал желтую линию в солнечном спектре, которая не соответствовала известным линиям натрия D1 и D2, и поэтому он назвал ее линией D3. Локьер пришел к выводу, что она была вызвана вещест [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HeliumHistory {
            get {
                return ResourceManager.GetString("HeliumHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ядро каждого атома гелия содержит два протона, но, как и у других элементов, у него есть изотопы. Они содержат от одного до шести нейтронов, поэтому их массовые числа находятся в диапазоне от трех до восьми. Стабильными из них являются элементы, у которых масса гелия определяется атомными числами 3 (3He) и 4 (4He). Все остальные радиоактивны и очень быстро распадаются на другие вещества. Земной гелий не является изначальной составляющей планеты, он образовался в результате радиоактивного распада. Альфа-част [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HeliumIsotopes {
            get {
                return ResourceManager.GetString("HeliumIsotopes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гелий – инертный газ 18-й группы периодической таблицы. Это второй самый легкий элемент после водорода. Гелий – газ без цвета, запаха и вкуса, который становится жидким при температуре -268.9 °C. Точки кипения и замерзания его ниже, чем у любого другого известного вещества. Это единственный элемент, который не затвердевает при охлаждении при нормальном атмосферном давлении. Чтобы гелий перешел в твердое состояние, необходимо 25 атмосфер при температуре 1 К..
        /// </summary>
        public static string HeliumMainDescription {
            get {
                return ResourceManager.GetString("HeliumMainDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Температура кипения и плавления у этого элемента самые низкие. По этой причине гелий существует в виде газа, за исключением экстремальных условий. Газообразный He в воде растворяется меньше, чем какой-либо другой газ, а скорость диффузии через твердые тела в три раза больше, чем у воздуха. Его показатель преломления ближе всего приближается к 1. Теплопроводность гелия уступает лишь теплопроводности водорода, а его удельная теплоемкость необычайно высокая. При обычных температурах при расширении он нагревает [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HeliumPhysicalProperties {
            get {
                return ResourceManager.GetString("HeliumPhysicalProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гелий (чистотой 98,2%) выделяют из природного газа путем сжижения других компонентов при низких температурах и при высоких давлениях. Адсорбция других газов охлажденным активированным углем позволяет добиться чистоты 99,995%. Небольшой объем гелия производится при сжижении воздуха в больших масштабах. Из 900 т воздуха можно получить около 3,17 куб. м газа..
        /// </summary>
        public static string HeliumProduction {
            get {
                return ResourceManager.GetString("HeliumProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Масса гелия составляет около 23% всей массы Вселенной, и элемент является вторым по распространенности в космосе. Он сосредоточен в звездах, где образуется из водорода в результате термоядерного синтеза. Хотя в земной атмосфере гелий находится в концентрации 1 часть на 200 тыс. (5 промилле) и в небольших количествах содержится в радиоактивных минералах, метеоритном железе, а также в минеральных источниках, большие объемы элемента встречаются в Соединенных Штатах (особенно в Техасе, Нью-Мексико, Канзасе, Окл [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HeliumSpread {
            get {
                return ResourceManager.GetString("HeliumSpread", resourceCulture);
            }
        }
    }
}
