//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NobleGasesMAUI.Elements.Neon {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Neon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Neon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NobleGasesMAUI.Elements.Neon.Neon", typeof(Neon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пятый по распространённости элемент Вселенной после водорода, гелия, кислорода и углерода. Газ без цвета и запаха..
        /// </summary>
        public static string Neon1 {
            get {
                return ResourceManager.GetString("Neon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Он практически ни с чем не вступает в активную химическую реакцию. Но при этом элемент обладает высокой электропроводностью..
        /// </summary>
        public static string Neon2 {
            get {
                return ResourceManager.GetString("Neon2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неон применяется: 
        ///•	Неону нашли широкое применение в промышленной сфере. Данный элемент выступает в качестве охладителя в криогенных установках. Жидкий неон идеально подходит для создания температуры для хранения ракетного топлива или для имитации космических условий.
        ///•	Благодаря хорошей электропроводности, неон используется в рекламе. Многие люди по ошибке воспринимают светящиеся надписи любого цвета за неоновые. В реальности это не так, потому что неон светится исключительно оранжево-красным или ярко-к [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Neon3 {
            get {
                return ResourceManager.GetString("Neon3", resourceCulture);
            }
        }
    }
}
